language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/board/.m2/repository'
    - '$HOME/board/.gradle'

script: "cd board ./gradlew clean build"

before_deploy:
- pwd
- zip -r hyo-springboot2-webservice *
- mkdir -p before_deploy
- mv hyo-springboot2-webservice.zip before_deploy/hyo-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: hyo-stringboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: before_deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  #  - provider: codedeploy
  #    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
  #    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
  #    bucket: hyo-stringboot-build # S3 버킷
  #    key: hyo-springboot2-webservice.zip # 빌드 파일을 압축해서 전달
  #    bundle_type: zip
  #    application: hyo-springboot2-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
  #    deployment_group: hyo-springboot2-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
  #    region: ap-northeast-2
  #    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - florida90@naver.com
